/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pdms.view;

/**
 *
 * @author Suresh
 */
public class NewCustomerFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public NewCustomerFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblTitle = new javax.swing.JLabel();
        jbtnSubmit = new javax.swing.JButton();
        jlblLandline = new javax.swing.JLabel();
        jlblerrName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxaAddress = new javax.swing.JTextArea();
        jlblerrAddress = new javax.swing.JLabel();
        jlblAddress = new javax.swing.JLabel();
        jlblerrPincode = new javax.swing.JLabel();
        jblMobile = new javax.swing.JLabel();
        jlblerrMobile = new javax.swing.JLabel();
        jtxtPhone = new javax.swing.JTextField();
        jlblerrLandline = new javax.swing.JLabel();
        jlblPincode = new javax.swing.JLabel();
        jlblerrAmount = new javax.swing.JLabel();
        jtxtPincode = new javax.swing.JTextField();
        jtxtStdCode = new javax.swing.JTextField();
        jtxtAmount = new javax.swing.JTextField();
        jlblAmount = new javax.swing.JLabel();
        jtxtMobile = new javax.swing.JTextField();
        jtxtName = new javax.swing.JTextField();
        jlblName = new javax.swing.JLabel();

        jlblTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTitle.setText("New Customer");
        jlblTitle.setToolTipText("");

        jbtnSubmit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnSubmit.setText("Submit");

        jlblLandline.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblLandline.setText("Landline No:");

        jlblerrName.setText("jLabel1");

        jtxaAddress.setColumns(20);
        jtxaAddress.setRows(5);
        jScrollPane1.setViewportView(jtxaAddress);

        jlblerrAddress.setText("jLabel2");

        jlblAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblAddress.setText("Adress:");

        jlblerrPincode.setText("jLabel3");

        jblMobile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jblMobile.setText("Mobile No:");

        jlblerrMobile.setText("jLabel4");

        jlblerrLandline.setText("jLabel5");

        jlblPincode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblPincode.setText("Pincode:");

        jlblerrAmount.setText("jLabel6");

        jtxtAmount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtAmount.setText("0.00");

        jlblAmount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblAmount.setText("Amount:");

        jlblName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblName.setText("Name:");
        jlblName.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jlblTitle)
                .addContainerGap(128, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlblName)
                                    .addComponent(jlblPincode)
                                    .addComponent(jblMobile)
                                    .addComponent(jlblAddress)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlblAmount)))
                        .addComponent(jlblLandline))
                    .addGap(19, 19, 19)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jbtnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtxtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtxtPincode, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jtxtStdCode, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtxtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jtxtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(3, 3, 3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1)
                                        .addComponent(jtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlblerrMobile, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jlblerrPincode, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jlblerrLandline, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jlblerrAmount, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblerrName)
                                    .addComponent(jlblerrAddress, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addContainerGap(36, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jlblTitle)
                .addContainerGap(367, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(66, 66, 66)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jtxtPincode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jlblerrPincode))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jtxtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jlblerrMobile))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jtxtStdCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtxtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jlblerrLandline))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtxtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jlblerrName)
                                            .addGap(90, 90, 90))
                                        .addComponent(jlblerrAddress))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlblerrAmount)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbtnSubmit))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(113, 113, 113)
                                    .addComponent(jlblPincode)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jblMobile)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jlblLandline)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jlblAmount))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jlblName)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jlblAddress)))
                            .addGap(6, 6, 6)))
                    .addGap(67, 67, 67)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jblMobile;
    private javax.swing.JButton jbtnSubmit;
    private javax.swing.JLabel jlblAddress;
    private javax.swing.JLabel jlblAmount;
    private javax.swing.JLabel jlblLandline;
    private javax.swing.JLabel jlblName;
    private javax.swing.JLabel jlblPincode;
    private javax.swing.JLabel jlblTitle;
    private javax.swing.JLabel jlblerrAddress;
    private javax.swing.JLabel jlblerrAmount;
    private javax.swing.JLabel jlblerrLandline;
    private javax.swing.JLabel jlblerrMobile;
    private javax.swing.JLabel jlblerrName;
    private javax.swing.JLabel jlblerrPincode;
    private javax.swing.JTextArea jtxaAddress;
    private javax.swing.JTextField jtxtAmount;
    private javax.swing.JTextField jtxtMobile;
    private javax.swing.JTextField jtxtName;
    private javax.swing.JTextField jtxtPhone;
    private javax.swing.JTextField jtxtPincode;
    private javax.swing.JTextField jtxtStdCode;
    // End of variables declaration//GEN-END:variables
}
