/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pdms.frame;

import com.pdms.display.InvoiceDisplay;
import com.pdms.display.InvoiceItemDisplay;
import com.pdms.display.ItemDisplay;
import com.pdms.frame.utils.CollectionResultTableModel;
import com.pdms.frame.utils.ServiceFactory;
import com.pdms.frame.utils.TableColumnAdjuster;
import com.pdms.service.ItemService;
import com.pdms.utils.DateUtils;
import com.pdms.utils.Utils;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractListModel;
import javax.swing.DefaultListModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Suresh
 */
public class InvoiceGeneratePanel extends javax.swing.JPanel {

    /**
     * Creates new form InvoiceGeneratePanel
     */
    String customerName;
    ItemService itemService;
    List<ItemDisplay> itemDisplays;
    InvoiceDisplay invoiceDisplay;
    
    public InvoiceGeneratePanel(String customerName) {
        initComponents();
        this.customerName = customerName;
        itemService = ServiceFactory.getItemService();
        loadDatas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblDog = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblContent = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        lblPayableAmount = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCustomerName = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblDiscount = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFromDate = new javax.swing.JTextField();
        txtToDate = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        listItems = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtDiscount = new javax.swing.JTextField();

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setText("To Date:");

        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotal.setText("TotalAmount");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setText("Total Amount: Rs");

        lblDog.setText("dog");

        jtblContent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Type", "Quantity", "Unit Price", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtblContent);

        jLabel5.setText("Date:");

        lblPayableAmount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPayableAmount.setText("Amount");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setText("Payable Amount: Rs");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setText("Customer Details:");

        lblCustomerName.setText("Name");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setText("Discount: Rs");

        lblDiscount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDiscount.setText("Discount");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setText("From Date:");

        txtFromDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFromDateActionPerformed(evt);
            }
        });

        listItems.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listItems.setVisibleRowCount(5);
        jScrollPane2.setViewportView(listItems);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setText("Items");

        btnSubmit.setBackground(new java.awt.Color(255, 255, 255));
        btnSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calculator.png"))); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel9.setText("Discount:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblDog)
                            .addGap(135, 135, 135)
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblPayableAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmit)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtDiscount, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtToDate, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtFromDate, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)))
                .addGap(122, 122, 122))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblCustomerName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtToDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSubmit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPayableAmount)
                    .addComponent(jLabel6))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblDiscount))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5)
                    .addComponent(lblTotal)
                    .addComponent(lblDog))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFromDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFromDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFromDateActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        calcuate();
    }//GEN-LAST:event_btnSubmitActionPerformed
    
    private void hideCloummn(String property) {
        jtblContent.getColumn(property).setWidth(0);
        jtblContent.getColumn(property).setMinWidth(0);
        jtblContent.getColumn(property).setMaxWidth(0);
    }
    
    private void loadDatas() {
        lblCustomerName.setText(customerName);
        lblDiscount.setText("0.00");
        txtFromDate.setText("");
        txtToDate.setText("");
        lblPayableAmount.setText("0.00");
        txtDiscount.setText("0.00");
        lblTotal.setText("0.00");
        lblDog.setText(DateUtils.getDateAsString(new Date()));
        List<InvoiceItemDisplay> invoiceItemDisplays = new ArrayList<>();
        TableModel tableModel = new CollectionResultTableModel<>(invoiceItemDisplays, InvoiceItemDisplay.class);
        
        jtblContent.setModel(tableModel);
        
        jScrollPane1.getViewport().add(jtblContent);
        hideCloummn("Id");
        
        itemDisplays();
        
    }
    
    void itemDisplays() {
        try {
            itemDisplays = itemService.getValidAll();
            DefaultListModel<String> listModel = new DefaultListModel<>();
            List<String> itemNames = new ArrayList<>();
            for (ItemDisplay itemDisplay : itemDisplays) {
                listModel.addElement(itemDisplay.getName());
            }
            listItems.setModel(listModel);
            
        } catch (Exception ex) {
            Logger.getLogger(InvoiceGeneratePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void calcuate() {
        try {
            int[] names = listItems.getSelectedIndices();
            double discount = 0, payableAmount = 0, totalAmount = 0;
            
            int quantityDates = (int) getQuantityDates();
            List<ItemDisplay> selectedItems = new ArrayList<>();
            for (int index : names) {
                selectedItems.add(itemDisplays.get(index));
            }
            
            List<InvoiceItemDisplay> invoiceItems = new ArrayList<>();
            
            for (ItemDisplay itemDisplay : selectedItems) {
                InvoiceItemDisplay invoiceItemDisplay = new InvoiceItemDisplay();
                invoiceItemDisplay.setItemDisplay(itemDisplay, quantityDates);
                invoiceItems.add(invoiceItemDisplay);
                payableAmount = payableAmount + Double.parseDouble(invoiceItemDisplay.getTotal());
            }
            CollectionResultTableModel tableModel = new CollectionResultTableModel(invoiceItems, InvoiceItemDisplay.class);
            jtblContent.setModel(tableModel);
            TableColumnAdjuster columnAdjuster = new TableColumnAdjuster(jtblContent);
            columnAdjuster.adjustColumns();
            jScrollPane1.setViewportView(jtblContent);
            hideCloummn("Id");
            
            discount = Double.parseDouble(txtDiscount.getText());
            totalAmount = payableAmount - discount;
            
            lblPayableAmount.setText(Utils.getDoubleValueAsMoney(payableAmount));
            lblDiscount.setText(Utils.getDoubleValueAsMoney(discount));
            lblTotal.setText(Utils.getDoubleValueAsMoney(totalAmount));

            //load Invoice
            invoiceDisplay = new InvoiceDisplay();            
            invoiceDisplay.setDog(lblDog.getText());
            invoiceDisplay.setFromDate(txtFromDate.getText());
            invoiceDisplay.setToDate(txtToDate.getText());            
            invoiceDisplay.setPayableAmount(lblPayableAmount.getText());
            invoiceDisplay.setDiscount(lblDiscount.getText());
            invoiceDisplay.setTotalAmount(lblTotal.getText());
            invoiceDisplay.setInvoiceItemDisplays(invoiceItems);
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    } 
    
    
    private long getQuantityDates() throws ParseException {
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        Date date1 = format.parse(txtFromDate.getText());
        Date date2 = format.parse(txtToDate.getText());
        long diff = date2.getTime() - date1.getTime();
        return TimeUnit.DAYS.convert(diff, TimeUnit.MILLISECONDS) + 1;
    }
    
    public InvoiceDisplay getInvoiceDisplay() {
        return invoiceDisplay;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtblContent;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblDiscount;
    private javax.swing.JLabel lblDog;
    private javax.swing.JLabel lblPayableAmount;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JList listItems;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtFromDate;
    private javax.swing.JTextField txtToDate;
    // End of variables declaration//GEN-END:variables

}
